# いろんなコードのベンチマーク

- time.time()とlineprofilerを使用

In [ ]:
import time 
start_perf = time.perf_counter()
print(start_perf)
start_time = time.time()
print(start_time)
time.sleep(1)
print(f'perf counter = {time.perf_counter() - start_perf}')
print(f'time = {start_time - time.time()}')

### 内包表記とforループ


In [ ]:
import time
import numpy as np


def comprehension(N):
    # 内包表記 
    comprehensions_list = [i for i in range(N)]
    # print(comprehensions_list)
    
    
def loop(N):
    loop_list = []
    for i in range(N):
        loop_list.append(i)
    # print(loop_list)


def numpy_arange(N):
    np_list = np.arange(N)
    
    # print(np_list)

def main():
    N = 10000
    start_time = time.time()
    comprehension(N)
    print(f'内包表記の処理時間 = {start_time - time.time()}')
    start_time = time.time()
    loop(N)
    print(f'ループの処理時間 = {start_time - time.time()}')
    
main()


- time.time()での実時間はline_profilerとは共存できない

In [ ]:
import time
import line_profiler 


def comprehension(N):
    # 内包表記 
    comprehensions_list = [i for i in range(N)]
    # print(comprehensions_list)
    

def main():
    N = 10000
    start_time = time.time()
    comprehension(N)
    print(f'内包表記の処理時間 = {start_time - time.time()}')

    
profile = line_profiler.LineProfiler()
profile.add_function(comprehension)
profile.runcall(main)
profile.print_stats(output_unit=1e-6)


In [3]:
import line_profiler 
import numpy as np


def comprehension(N):
    # 内包表記 
    comprehensions_list = [i for i in range(N)]
    # print(comprehensions_list)
    
    
def loop(N):
    loop_list = []
    for i in range(N):
        loop_list.append(i)
    # print(loop_list)


def numpy_arange(N):
    np_list = np.arange(N)
    
    # print(np_list)

def main():
    N = 10000
    comprehension(N)
    loop(N)
    numpy_arange(N)


profile = line_profiler.LineProfiler()
profile.add_function(comprehension)
profile.add_function(loop)
profile.add_function(numpy_arange)
profile.runcall(main)
profile.print_stats(output_unit=1e-6)


Timer unit: 1e-06 s

Total time: 0.0023165 s
File: C:\Users\fujikawa\AppData\Local\Temp\ipykernel_14860\123265391.py
Function: comprehension at line 5

Line #      Hits         Time  Per Hit   % Time  Line Contents
     5                                           def comprehension(N):
     6                                               # 内包表記 
     7         1       2316.5   2316.5    100.0      comprehensions_list = [i for i in range(N)]
     8                                               # print(comprehensions_list)

Total time: 0.0043904 s
File: C:\Users\fujikawa\AppData\Local\Temp\ipykernel_14860\123265391.py
Function: loop at line 11

Line #      Hits         Time  Per Hit   % Time  Line Contents
    11                                           def loop(N):
    12         1          0.8      0.8      0.0      loop_list = []
    13     10000       1856.8      0.2     42.3      for i in range(N):
    14     10000       2532.8      0.3     57.7          loop_list.append(i)
    15  

- cProfiler  
関数のみ対象  
相対的なものは解るが実測ではない

In [4]:
import io
import cProfile 
import pstats
from pstats import SortKey
import numpy as np


def comprehension(N):
    # 内包表記 
    comprehensions_list = [i for i in range(N)]
    # print(comprehensions_list)
    
    
def loop(N):
    loop_list = []
    for i in range(N):
        loop_list.append(i)
    # print(loop_list)


def numpy_arange(N):
    np_list = np.arange(N)
    
    # print(np_list)


def main():
    N = 1000000
    test_profiler=cProfile.Profile(timeunit=.000000000001)
    test_profiler.enable()
    comprehension(N)
    test_profiler.disable()
    s = io.StringIO()
    sortkey = SortKey.CUMULATIVE
    ps = pstats.Stats(test_profiler, stream=s).sort_stats(sortkey)
    ps.print_stats(20)
    sortkey = SortKey.TIME
    ps = pstats.Stats(test_profiler, stream=s).sort_stats(sortkey)
    ps.print_callers(.5, 'init')
    ps.print_stats(20)
    print(s.getvalue())
    
    test_profiler=cProfile.Profile(timeunit=.000000000001)
    test_profiler.enable()
    loop(N)
    test_profiler.disable()
    s = io.StringIO()
    sortkey = SortKey.CUMULATIVE
    ps = pstats.Stats(test_profiler, stream=s).sort_stats(sortkey)
    ps.print_stats(20)
    sortkey = SortKey.TIME
    ps = pstats.Stats(test_profiler, stream=s).sort_stats(sortkey)
    ps.print_callers(.5, 'init')
    ps.print_stats(20)
    print(s.getvalue())
    
    test_profiler=cProfile.Profile(timeunit=.000000000001)
    test_profiler.enable()
    numpy_arange(N)
    test_profiler.disable()
    s = io.StringIO()
    sortkey = SortKey.CUMULATIVE
    ps = pstats.Stats(test_profiler, stream=s).sort_stats(sortkey)
    ps.print_stats(20)
    sortkey = SortKey.TIME
    ps = pstats.Stats(test_profiler, stream=s).sort_stats(sortkey)
    ps.print_callers(.5, 'init')
    ps.print_stats(20)
    print(s.getvalue())


main()

         3 function calls in 0.042 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    0.042    0.042 C:\Users\fujikawa\AppData\Local\Temp\ipykernel_14860\2187775345.py:8(comprehension)
        1    0.042    0.042    0.042    0.042 C:\Users\fujikawa\AppData\Local\Temp\ipykernel_14860\2187775345.py:10(<listcomp>)
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}


         3 function calls in 0.042 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.042    0.042    0.042    0.042 C:\Users\fujikawa\AppData\Local\Temp\ipykernel_14860\2187775345.py:10(<listcomp>)
        1    0.000    0.000    0.042    0.042 C:\Users\fujikawa\AppData\Local\Temp\ipykernel_14860\2187775345.py:8(comprehension)
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects

- cProfilerのデコレータ

In [6]:
import cProfile 
import pstats
from pstats import SortKey

import os
import numpy as np

def apply_cprofiler(func):
    
    def wrapper(*args, **kwargs):
        test_profiler=cProfile.Profile(timeunit=.01)
        test_profiler.runcall(func, *args, **kwargs)

        # 関数の総処理時間でソート
        sortkey = SortKey.CUMULATIVE
        ps = pstats.Stats(test_profiler).sort_stats(sortkey)
        ps.print_stats(20)
        # 行番号でソート
        sortkey = SortKey.NFL
        ps = pstats.Stats(test_profiler).sort_stats(sortkey)
        ps.print_callers(.5, 'init')
        ps.print_stats(20)
        # 関数の呼び出し関係を表示
        ps.print_callees()
    return wrapper

@apply_cprofiler
def comprehension(N):
    # 内包表記 
    comprehensions_list = [i for i in range(N)]
    # print(comprehensions_list)
    
@apply_cprofiler   
def loop(N):
    loop_list = []
    for i in range(N):
        loop_list.append(i)
    # print(loop_list)

@ apply_cprofiler
def numpy_arange(N):
    np_list = np.arange(N)
    
    # print(np_list)

def main():
    N = 1000000

    comprehension(N)
    loop(N)
    numpy_arange(N)


main()

         3 function calls in 0.045 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    0.045    0.045 C:\Users\fujikawa\AppData\Local\Temp\ipykernel_14860\2903165328.py:27(comprehension)
        1    0.045    0.045    0.045    0.045 C:\Users\fujikawa\AppData\Local\Temp\ipykernel_14860\2903165328.py:30(<listcomp>)
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}


         3 function calls in 0.045 seconds

   Ordered by: name/file/line

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.045    0.045    0.045    0.045 C:\Users\fujikawa\AppData\Local\Temp\ipykernel_14860\2903165328.py:30(<listcomp>)
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}
        1    0.000    0.000    0.045    0.045 C:\Users\fujikawa\AppData\Local\Temp\ipykernel_14860\2903165328.py:27(comprehens

- スライスでreplace

In [24]:
import numpy as np
N = 24
X = 2
Y = 3
Z = 4
aranged_list = np.arange(N)
array = aranged_list.reshape((X, Y, Z))
print(array)

# 表示用　u要素番号の、2次元配列のv列番号をリストにする
u = 1
v = 2
print(array[u, :, v])
# print([])


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[14 18 22]
