# 出力、変数のフォーマット

In [4]:
a = 123
print(str(a).zfill(5))
print(f'{a:05}')
print(f'{str(a):05}')
b = -123
print(str(b).zfill(5))
print(f'{b:05}')
print(f'{str(b):05}')
c = 1.23
print(str(c).zfill(5))
print(f'{c:05}')
print(f'{str(c):05}')


00123
00123
12300
-0123
-0123
-1230
01.23
01.23
1.230


### numpyやfloatの数値末尾の処理
np.format_float_positional

In [2]:
import numpy as np

SAVE_FILE = 'format_test.txt'

step = 0.1
start = 5.0
size = 51
data = []
for i in range(size):
    data.append((step * i) + start)

u_data = []
f_data = []
t_0_data = []
t_p_data = []
t_m_data = []
t_m8_data = []
print(data)

for i,value in enumerate(data):
    data[i] = np.format_float_positional(value, precision=14)
    u_data.append(np.format_float_positional(value, precision=14, unique=False))
    f_data.append(np.format_float_positional(value, precision=14, fractional=False))
    # Controls post-processing trimming of trailing digits
    t_0_data.append(np.format_float_positional(value, precision=14, trim='0'))
    t_p_data.append(np.format_float_positional(value, precision=14, trim='.'))
    t_m_data.append(np.format_float_positional(value, precision=14, trim='-'))
    t_m8_data.append(np.format_float_positional(value, precision=8, trim='-'))
print(data)
print(u_data)
print(f_data)
print(t_0_data)
print(t_p_data)
print(t_m_data)
print(t_m8_data)

print(*data)

with open(SAVE_FILE, 'w') as fs:
    fs.write(str(data))
    fs.write('\n')
    print(f_data, file=fs)
    print(t_0_data, file=fs)
    print(t_p_data, file=fs)
    print(t_m_data, file=fs)
    print(*data, file=fs)
    



[5.0, 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6.0, 6.1, 6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7.0, 7.1, 7.2, 7.300000000000001, 7.4, 7.5, 7.6, 7.7, 7.800000000000001, 7.9, 8.0, 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9.0, 9.100000000000001, 9.2, 9.3, 9.4, 9.5, 9.600000000000001, 9.7, 9.8, 9.9, 10.0]
['5.', '5.1', '5.2', '5.3', '5.4', '5.5', '5.6', '5.7', '5.8', '5.9', '6.', '6.1', '6.2', '6.3', '6.4', '6.5', '6.6', '6.7', '6.8', '6.9', '7.', '7.1', '7.2', '7.30000000000000', '7.4', '7.5', '7.6', '7.7', '7.80000000000000', '7.9', '8.', '8.1', '8.2', '8.3', '8.4', '8.5', '8.6', '8.7', '8.8', '8.9', '9.', '9.10000000000000', '9.2', '9.3', '9.4', '9.5', '9.60000000000000', '9.7', '9.8', '9.9', '10.']
['5.00000000000000', '5.10000000000000', '5.20000000000000', '5.30000000000000', '5.40000000000000', '5.50000000000000', '5.60000000000000', '5.70000000000000', '5.80000000000000', '5.90000000000000', '6.00000000000000', '6.10000000000000', '6.20000000000000', '6.30000000000000', '

### str -> int等の変換

In [2]:
str_int = '0001'
int_data = int(str_int)
print(int_data)

1


### ndaarryの表示
- ndarryとlistではprint表示に違いがある
- ndarryは小数点以下が0の時.だけで終わる
- float32からfloat64への変換は切りの悪い数値になる  
floatによるキャストが良い

In [3]:
import numpy as np
a = [790.15, 790.16, 790]
b = np.array(a, dtype=np.float32)
for value in b:
     print(np.format_float_positional(value, precision=14, trim='-'))
c = []

for value in a:
    float_value = float(value)
    c.append(float_value)
    print(np.format_float_positional(float_value, precision=14, trim='-'))
d = b.astype(np.float64)
e = np.array(c)
f = np.array(a, dtype=np.float64)

print(a)
print(b)
print(c)
print(d)
print(e)
print(f)
np.set_printoptions(suppress=False, precision=8, floatmode='fixed')
print('set options')
print(d)
print(e)
print(f)


790.15
790.16
790
790.15
790.16
790
[790.15, 790.16, 790]
[790.15002441 790.15997314 790.00000000]
[790.15, 790.16, 790.0]
[790.15002441 790.15997314 790.00000000]
[790.15000000 790.16000000 790.00000000]
[790.15000000 790.16000000 790.00000000]
set options
[790.15002441 790.15997314 790.00000000]
[790.15000000 790.16000000 790.00000000]
[790.15000000 790.16000000 790.00000000]
