# ラムダ関数のいろいろテスト

- リスト内包表記処理に組み込む

オリジナル

In [7]:
import numpy as np

parameters = [{1: [10, 11, 12], 10: [100, 101, 102], 'text': 'one'}, {1: [20, 21, 22], 10: [201, 201, 202], 'text': 'two'}]

print(np.stack([parameters[0][1], parameters[0][10]], 1))
norm_args = [["A", np.stack([para[1], para[10]], 1),
            f'FT k-weight={str(para["text"])}'] for para in parameters]
print(norm_args)

[[ 10 100]
 [ 11 101]
 [ 12 102]]
[['A', array([[ 10, 100],
       [ 11, 101],
       [ 12, 102]]), 'FT k-weight=one'], ['A', array([[ 20, 201],
       [ 21, 201],
       [ 22, 202]]), 'FT k-weight=two']]


ラムダ関数

In [9]:
import numpy as np

parameters = [{1: [10, 11, 12], 10: [100, 101, 102], 'text': 'one'}, {1: [20, 21, 22], 10: [201, 201, 202], 'text': 'two'}]

lam_func1 = lambda para: np.stack([para[1], para[10]], 1)
lam_func2 = lambda para: f'FT k-weight={str(para["text"])}'

print(np.stack([parameters[0][1], parameters[0][10]], 1))
norm_args = [["A", lam_func1(para),
            lam_func2(para)] for para in parameters]
print(norm_args)

[[ 10 100]
 [ 11 101]
 [ 12 102]]
[['A', array([[ 10, 100],
       [ 11, 101],
       [ 12, 102]]), 'FT k-weight=one'], ['A', array([[ 20, 201],
       [ 21, 201],
       [ 22, 202]]), 'FT k-weight=two']]


ラムダ関数を引数にできるか

In [11]:
import numpy as np


class Func:
    stack_func = lambda para: np.stack([para[1], para[10]], 1)
    string_func = lambda para: f'FT k-weight={str(para["text"])}'
    

parameters = [{1: [10, 11, 12], 10: [100, 101, 102], 'text': 'one'}, {1: [20, 21, 22], 10: [201, 201, 202], 'text': 'two'}]

# lam_func1 = lambda para: np.stack([para[1], para[10]], 1)
# lam_func2 = lambda para: f'FT k-weight={str(para["text"])}'

print(np.stack([parameters[0][1], parameters[0][10]], 1))
norm_args = [["A", Func.stack_func(para),
            Func.string_func(para)] for para in parameters]
print(norm_args)

[[ 10 100]
 [ 11 101]
 [ 12 102]]
[['A', array([[ 10, 100],
       [ 11, 101],
       [ 12, 102]]), 'FT k-weight=one'], ['A', array([[ 20, 201],
       [ 21, 201],
       [ 22, 202]]), 'FT k-weight=two']]
