In [1]:
import numpy as np
def sample():
    a=[1,2,3]
    b=[[4,5],[6,7]]
    return a, b
c=[[]*i for i in range(2)]
c[0], c[1] = sample()
d=[]
f=[]

for i in range(2):
    d.extend(c[i])
    f.append(c[i])

a_copy=np.empty((3,2,3))

print(d)
print(f)
a1 = np.ones((2, 3,15), int)
print(a1)
a2 = np.full((2, 4,15), 2)
print(a2)
a0 = np.zeros((2,7,15))

print(a0)
a_b=np.empty((2,7,15))
print(f"a1[0],a2[0]=\n{a1[0]},\n{a2[0]}\n")
print(f"insert=\n{np.insert(a1[0],3,a2[0][0:4],axis=0)}\n")
print(f"a1=\n{a1}\n")
a_buf=np.vstack([a1[0],a2[0]])
print(f"a_buf=\n{a_buf}\n")

a_b=np.vstack([a_buf,a0[0]])
print(f"a_b=\n{a_b}\n")
print(f"resize=\n{np.reshape(a_b,(2,7,15))}\n")

orig_arr=[]
ns=2
for i in range(3):
    n_arr=np.full((ns,1,15),i)
    print(f"n_arr=\n{n_arr}\n")
    for n in range(ns):
        if i == 0 == n:
            orig_arr=np.copy(n_arr[n])
            print(f"copied,n_arr{n} = \n{orig_arr},\n{n_arr[n]}\n")
        else:
            orig_arr=np.insert(orig_arr,i+(i+1)*n,n_arr[n],axis=0)
            print(f"stacked,n_arr{n} = \n{orig_arr},\n{n_arr[n]}\n")
print(f"reshape orig=\n{np.reshape(orig_arr,(ns,3,15))}")

#a_tot=np.empty((2,3))
a_tot=[]
print(f"shape={a1[0].shape}")
d1,d2,d3=a1.shape
print(f"d1,d2,d3={d1},{d2},{d3}")
print(f"dim={a1.ndim}")
print(f"size={a1.size}")
print(f"size={a1[0][:].size}")
for i,a in enumerate([a1,a2,a0]):
    if i == 0:
        a_tot=np.copy(a[0])
        print(f"atot = \n{a_tot}")
    if i > 0:
        a_tot=np.vstack([a_tot,a[0]])
        print(f"atot = \n{a_tot}")
print(f"total={a_tot}")

[1, 2, 3, [4, 5], [6, 7]]
[[1, 2, 3], [[4, 5], [6, 7]]]
[[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]]

 [[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]]]
[[[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]
  [2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]
  [2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]
  [2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]]

 [[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]
  [2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]
  [2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]
  [2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]]]
[[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.

In [ ]:
import numpy as np
n=3
a=np.zeros((n,2,3))
print(a)
print(a[0])

def assign_func(a, i):
    a_buf=np.full((2,3),i)
    a[i]=a_buf
    del a_buf
for i in range(n):
    assign_func(a, i)
print(f"assigned a=\n{a}\n")

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]
[[0. 0. 0.]
 [0. 0. 0.]]
assigned a=
[[[0. 0. 0.]
  [0. 0. 0.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[2. 2. 2.]
  [2. 2. 2.]]]



In [3]:
import numpy as np
n=2
l=3
a = np.arange(n*l*3)
a = np.reshape(a, [n, l, 3])
print(f'a = {a}')
b = np.copy(a)
def assign_func(a, b, i):
    global n
    a_temp = [[[i+1 for _ in range(3)] ]for i in range(n)]
    b_temp = [[i+1 for _ in range(3)] for i in range(n)]
    print(f'a temp = {a_temp}')
    print(f'b temp = {b_temp}')
    a_buf=np.array(a_temp)
    print(f'a_buf = {a_buf}')
    print(f'a[:, i, :] = {a[:, i, :]}')
    print(f'a_buf[:, 0, :] = {a_buf[:, 0, :]}')
    a[:, i, :]=a_buf[:, 0, :]
    print(f'assigned a_buf[:, 0, :] into a[:, i, :] = {a}')
    b_buf=np.array(b_temp)
    print(f'b_buf = {b_buf}')
    print(f'b[:, i, :] = {b[:,i, :]}')
    print(f'b_buf[:, :] = {b_buf[:, :]}')
    b[:, i, :]=b_buf[:, :]
    print(f'assigned b_buf[:, :] into b[:, i, :] = {b}')

    del a_buf
    
for i in range(l):
    assign_func(a, b, i)


a = [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]
a temp = [[[1, 1, 1]], [[2, 2, 2]]]
b temp = [[1, 1, 1], [2, 2, 2]]
a_buf = [[[1 1 1]]

 [[2 2 2]]]
a[:, i, :] = [[ 0  1  2]
 [ 9 10 11]]
a_buf[:, 0, :] = [[1 1 1]
 [2 2 2]]
assigned a_buf[:, 0, :] into a[:, i, :] = [[[ 1  1  1]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 2  2  2]
  [12 13 14]
  [15 16 17]]]
b_buf = [[1 1 1]
 [2 2 2]]
b[:, i, :] = [[ 0  1  2]
 [ 9 10 11]]
b_buf[:, :] = [[1 1 1]
 [2 2 2]]
assigned b_buf[:, :] into b[:, i, :] = [[[ 1  1  1]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 2  2  2]
  [12 13 14]
  [15 16 17]]]
a temp = [[[1, 1, 1]], [[2, 2, 2]]]
b temp = [[1, 1, 1], [2, 2, 2]]
a_buf = [[[1 1 1]]

 [[2 2 2]]]
a[:, i, :] = [[ 3  4  5]
 [12 13 14]]
a_buf[:, 0, :] = [[1 1 1]
 [2 2 2]]
assigned a_buf[:, 0, :] into a[:, i, :] = [[[ 1  1  1]
  [ 1  1  1]
  [ 6  7  8]]

 [[ 2  2  2]
  [ 2  2  2]
  [15 16 17]]]
b_buf = [[1 1 1]
 [2 2 2]]
b[:, i, :] = [[ 3  4  5]
 [12 13 14]]
b_buf[:, :] = [[1 1 1]
 [2 2 2]]
a

In [ ]:
import numpy as np
n=2
l=3
a=np.zeros((n,l,3))
print(a)
print(a[0])

def assign_func(a, i):
    global n
    a_buf=np.full((n,1,3),i)
    # a[0][i]=a_buf[0]
    print(f'a_buf = {a_buf}')
    a[:,i,:]=a_buf[:,0,:]

    del a_buf
for i in range(n):
    assign_func(a, i)
print(f"assigned a=\n{a}\n")

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
a_buf = [[[0 0 0]]

 [[0 0 0]]]
a_buf = [[[1 1 1]]

 [[1 1 1]]]
assigned a=
[[[0. 0. 0.]
  [1. 1. 1.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [1. 1. 1.]
  [0. 0. 0.]]]



In [ ]:
import numpy as np
arr = np.zeros([1, 3])
row = np.full((15,7), 100)
print(row)
additional = np.array([[1, 2, 3], [4, 5, 6]])
arr = np.r_[arr, additional][1:]
print(arr)


[[100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100]]
[[1. 2. 3.]
 [4. 5. 6.]]


In [ ]:
a0= [1 for _ in range(2)]
print(a0)
a3=[2 for _ in range(2)]
a1 = [0 for _ in range(5)]
print(f"a1={a1}\n")
a2 = [[1,2,3],[4,5,6]]
print(f"a2=\n{a2}")
a4=['a']
a0.extend(a4)
print(f"extend={a0}\n")
a1[2]=a2

print(f"a1={a1}\n")



In [ ]:
import numpy as np
a1 = np.ones((2, 3,15), int)
print(a1)
a2 = np.full((2,4,15), 2)
print(a2)
d1=2
d2=2
row=[i+15*((d1-1)*3+(d2-1)) for i in range(15)]
print(f"row={row}")
np.put(a1,row,a2[0][0])
print(f"replaced a1=\n{a1}\n")

In [ ]:
import numpy as np
a = np.arange(50)
a = np.reshape(a,(5,10))
print(a)
b = np.arange(0, 100, 2)
b = np.reshape(b,(5,10))
print(b)
c = np.arange(50, 0,-1)
c = np.reshape(c,(5,10))
print(c)
print(f"a0=\n{a[[0]]}\n")
arr_st = np.stack([a, b, c], 1)
print(arr_st)
for aa,bb,cc in zip(a, b, c):
    arr_st = np.stack([aa, bb, cc], 1)
print(f"arr_st=\n{arr_st}\n")

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
[[ 0  2  4  6  8 10 12 14 16 18]
 [20 22 24 26 28 30 32 34 36 38]
 [40 42 44 46 48 50 52 54 56 58]
 [60 62 64 66 68 70 72 74 76 78]
 [80 82 84 86 88 90 92 94 96 98]]
[[50 49 48 47 46 45 44 43 42 41]
 [40 39 38 37 36 35 34 33 32 31]
 [30 29 28 27 26 25 24 23 22 21]
 [20 19 18 17 16 15 14 13 12 11]
 [10  9  8  7  6  5  4  3  2  1]]
a0=
[[0 1 2 3 4 5 6 7 8 9]]

[[[ 0  1  2  3  4  5  6  7  8  9]
  [ 0  2  4  6  8 10 12 14 16 18]
  [50 49 48 47 46 45 44 43 42 41]]

 [[10 11 12 13 14 15 16 17 18 19]
  [20 22 24 26 28 30 32 34 36 38]
  [40 39 38 37 36 35 34 33 32 31]]

 [[20 21 22 23 24 25 26 27 28 29]
  [40 42 44 46 48 50 52 54 56 58]
  [30 29 28 27 26 25 24 23 22 21]]

 [[30 31 32 33 34 35 36 37 38 39]
  [60 62 64 66 68 70 72 74 76 78]
  [20 19 18 17 16 15 14 13 12 11]]

 [[40 41 42 43 44 45 46 47 48 49]
  [80 82 84 86 88 90 92

In [ ]:
import numpy as np
max_number = 3
x = 2
y = 15
#test_profiler=cProfile.Profile()
#test_profiler.enable()
a_l=np.zeros((max_number,x,y))
a = np.full((3),2)
b = np.full((3),3)
variables = np.zeros((y))
a_l[0,0,0] = 1
a_l[0,0,1:4] = a
a_l[0,0,4:7] = b*2
print(a_l)

[[[1. 2. 2. 2. 6. 6. 6. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]]


In [ ]:
import numpy as np
a = np.zeros((2,3))
print(a)
a[:,0] = 1
print(a)

print(np.sum(a[0,1:]))
print(np.sum(a[1,1:]))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [1. 0. 0.]]
0.0
0.0


In [ ]:
import numpy as np
import random

M = 2
N = 5

# サンプルデータを作る（N 次元ベクトルを M 個生成してリストに格納）
mu = [2 * np.random.rand(N, 2) - 1 for _ in range(M)]
header = [f'{i}\ncolumn1\tcolumn2' for i in range(M)]
print(header)
# N 次元ベクトルを辞書に格納する
d = {f'mu_{i}.txt': mu[i] for i in range(M)}

# 保存する
np.savez('./mu_params', **d)  # dict のアンパックが必要
#np.save('headerbin.npy', header)
np.savetxt('header.txt', header, fmt='%s')
# 読み込む
d = np.load('./mu_params.npz')  # 拡張子 .npz の指定が必要
#h = np.load('headerbin.npy')
h = np.loadtxt('header.txt', dtype='str')
# 辞書からリストを復元する
for filename,header in zip(d, h):
    np.savetxt(filename, d[filename], header=header, delimiter='\t')
#d_list = d.files  # arrayの名前リストを取得


In [ ]:
for l_n, header_l in zip(loaded_npz, header_list):
            np.savetxt(os.path.join(directory, SAVE_DIRECTORY, l_n), loaded_npz[l_n], header=header_l, delimiter='\t')

In [ ]:
import time
import numpy as np
start = time.time()
print(start)
a = ["a", "b", "c"]
np.savetxt("testsavetxt.txt",a, fmt="%s")
#for _ in range(3):
b = np.loadtxt("testsavetxt.txt", dtype="str")
print(b)
    


In [22]:
import numpy as np
n = 5000
a = [[i for i in range(n) ] for _ in range(n)]
b = []
for x in a:
    c = []
    for y in x:
        c.append(y*2)
    b.append(c)

