# numpyのテスト

### float32の出力 (f4)
- 小数点8桁目までしか使用できない

In [3]:
import numpy as np
np.set_printoptions(suppress=False, precision=14, floatmode='fixed')
a = np.array([123456789012345678, 0.000001234567890123456789, 0], dtype=np.float32)
print(a)
for d1 in a:
    print(np.format_float_positional(d1, precision=14, unique=False))
    print(np.format_float_positional(d1, precision=14, trim='-'))
    print(np.format_float_scientific(d1, precision=14, unique=False))
    print(np.format_float_scientific(d1, precision=14, trim='-'))


[1.23456790519087e+17 1.23456788969634e-06 0.00000000000000e+00]
123456790519087104.00000000000000
123456790000000000
1.23456790519087e+17
1.2345679e+17
0.00000123456789
0.0000012345679
1.23456788969634e-06
1.2345679e-06
0.00000000000000
0
0.00000000000000e+00
0e+00


### float64だと

In [7]:
import numpy as np
np.set_printoptions(suppress=False, precision=14, floatmode='fixed')
a = np.array([123456789012345678, 0.000001234567890123456789, 0], dtype=np.float64)
print(a)
for d1 in a:
    print(np.format_float_positional(d1, precision=14, unique=False))
    print(np.format_float_positional(d1, precision=14, trim='-'))
    print(np.format_float_scientific(d1, precision=14, unique=False))
    print(np.format_float_scientific(d1, precision=14, trim='-'))


[1.23456789012346e+17 1.23456789012346e-06 0.00000000000000e+00]
123456789012345680.00000000000000
123456789012345680
1.23456789012346e+17
1.23456789012346e+17
0.00000123456789
0.00000123456789
1.23456789012346e-06
1.23456789012346e-06
0.00000000000000
0
0.00000000000000e+00
0e+00


### format_float_scientificでフォーマット可能
- 出力はstrなので注意
- precisionはset_printoptionと同じで小数点以下の有効桁数

In [2]:
import numpy as np
pi = np.format_float_scientific(np.float32(np.pi), precision=6)
print(f'pi:{type(pi)} = {pi}')
print(np.format_float_scientific(12345.67890123, precision=6))
np.set_printoptions(suppress=True, precision=6, floatmode='fixed')
list = [12345.67890123, 0.1234567890]
array = np.array(list)
print(array)

pi:<class 'str'> = 3.141593e+00
1.234568e+04
[12345.678901     0.123457]


### np.format_float_positionalのprecisionはp.set_printoptionsの影響を受けない

In [1]:
# NOTE:restartが必要
import numpy as np

PRECISION = 16
a = np.empty(3, dtype=np.float32)
print(a)
for d1 in a:
    print(np.format_float_positional(d1, precision=PRECISION))
a = np.empty(3, dtype=np.float64)
print(a)
b = np.array([1234567890123456789, 0.000001234567890123456789], dtype=np.float64)
print(b)
c = np.array([1234567890123456789, 0.000001234567890123456789], dtype=np.float32)
print(c)
print('float64')
for d1 in b:
    print(np.format_float_positional(d1, precision=PRECISION, unique=False))
    print(np.format_float_positional(d1, precision=PRECISION))
print('float32')
for d1 in c:
    print(np.format_float_positional(d1, precision=PRECISION, unique=False))
    print(np.format_float_positional(d1, precision=PRECISION))
np.set_printoptions(suppress=False, precision=PRECISION, floatmode='fixed')
print(f'set print option precision = {PRECISION}')
a = np.empty(3, dtype=np.float32)
print(a)
for d1 in a:
    print(np.format_float_positional(d1, precision=PRECISION))
a = np.empty(3, dtype=np.float64)
print(a)
b = np.array([1234567890123456789, 0.000001234567890123456789], dtype=np.float64)
print(b)
c = np.array([1234567890123456789, 0.000001234567890123456789], dtype=np.float32)
print(c)
print('float64')
for d1 in b:
    print(np.format_float_positional(d1, precision=PRECISION, unique=False))
    print(np.format_float_positional(d1, precision=PRECISION))
print('float32')
for d1 in c:
    
    print(np.format_float_positional(d1, precision=PRECISION, unique=False))
    print(np.format_float_positional(d1, precision=PRECISION))


[4.6124454e-13 3.9675042e-38 2.4355531e+33]
0.0000000000004612
0.0000000000000000
2435553100000000000000000000000000.
[1.44932313e-311 1.34017630e-272 1.31357666e-311]
[1.23456789e+18 1.23456789e-06]
[1.2345679e+18 1.2345679e-06]
float64
1234567890123456768.0000000000000000
1234567890123456800.
0.0000012345678901
0.0000012345678901
float32
1234567939550609408.0000000000000000
1234568000000000000.
0.0000012345678897
0.0000012345679
set print option precision = 16
[4.6124454082530075e-13 3.9675041893142548e-38 2.4355530985935049e+33]
0.0000000000004612
0.0000000000000000
2435553100000000000000000000000000.
[1.4493231255642575e-311 1.3401763046420495e-272 1.3135766566586783e-311]
[1.2345678901234568e+18 1.2345678901234567e-06]
[1.2345679395506094e+18 1.2345678896963364e-06]
float64
1234567890123456768.0000000000000000
1234567890123456800.
0.0000012345678901
0.0000012345678901
float32
1234567939550609408.0000000000000000
1234568000000000000.
0.0000012345678897
0.0000012345679


### 小数点以下のごみを取りたい
- float32のままではsavetxtの出力には7.90150024E+02のようになる  
対応策としてfloat64に直す

In [12]:
# NOTE:restartが必要
import numpy as np

PRECISION = 8

    # print(np.format_float_positional(d1, precision=PRECISION))
a = np.array([790.15, 790.16, 790], dtype=np.float32)
print(a)
np.set_printoptions(suppress=False, precision=PRECISION)

print(a)

np.savetxt('float32.txt', a, fmt='%1.8E')
np.set_printoptions()
b = []
for value in a:
    
    str_value = str(value)
    float_value = float(str_value)
    b.append(float_value)
np.savetxt('float.txt', b, fmt='%1.8E')
print(b)

d = [790.15, 790.16, 790]
print(d)
# b = np.array([1234567890123456789, 0.000001234567890123456789], dtype=np.float64)

[790.15 790.16 790.  ]
[790.15 790.16 790.  ]
[790.15, 790.16, 790.0]
[790.15, 790.16, 790]


In [4]:
# NOTE:restartが必要
import numpy as np

PRECISION = 8

    # print(np.format_float_positional(d1, precision=PRECISION))
a = np.array([790.15, 790.16], dtype=np.float64)
print(a)
np.set_printoptions(suppress=False, precision=PRECISION)

print(a)
np.savetxt('float64.txt', a, fmt='%1.8E')
# b = np.array([1234567890123456789, 0.000001234567890123456789], dtype=np.float64)

[790.15 790.16]
[790.15 790.16]


In [14]:
import numpy as np
np.set_printoptions(suppress=False, precision=14, floatmode='fixed')
# np.set_printoptions(suppress=False, precision=14, floatmode='maxprec_equal')
SAVE_FILE = 'nptest.dat'
a = np.empty(3, dtype=np.float32)
print(a)
for d1 in a:
    print('zero float32')
    np.set_printoptions(suppress=False, precision=14, floatmode='fixed')

    print(d1)
    print(np.format_float_positional(d1, precision=14))
    print(np.format_float_scientific(d1, precision=14))
    print(np.format_float_scientific(d1, precision=14, exp_digits=4))
    print('reset')    
    np.set_printoptions()
    print(np.format_float_positional(d1, precision=8, trim='-'))

a = np.empty(3, dtype=np.float64)
print(a)
for d1 in a:
    print('zero float64')
    np.set_printoptions(suppress=False, precision=14, floatmode='fixed')

    print(d1)
    print(np.format_float_positional(d1, precision=14))
    print(np.format_float_scientific(d1, precision=14))
    print(np.format_float_scientific(d1, precision=14, exp_digits=4))
    np.set_printoptions()
    print('reset')
    print(np.format_float_positional(d1, precision=8, trim='-'))
    
b = np.array([123456789012345678, 0.000001234567890123456789], dtype=np.float32)
print(b)
np.savetxt(SAVE_FILE, b)
z = np.empty((3, 3), dtype=np.float64)

with open(SAVE_FILE, 'a+') as fs:
    fs.write('# save float 32\n')
    fs.write('# array b\n')

    np.savetxt(fs, b, fmt='%.8E', delimiter=' ')
    fs.write('# array z\n')
    np.savetxt(fs, z, fmt='%.8E', delimiter=' ')
    
for d1 in b:
    print('d1 float 32')
    print(np.format_float_positional(d1, precision=14, unique=False))
    print(np.format_float_scientific(d1, precision=14, unique=False))
    print()
    print(np.format_float_positional(d1, precision=14))
    print(np.format_float_scientific(d1, precision=14))
    print(np.format_float_scientific(d1, precision=14, exp_digits=4))
    print()
    print(np.format_float_positional(d1, precision=8))
    print(np.format_float_scientific(d1, precision=8))
       
b = np.array([123456789012345678, 0.000000000000001234567890123456789], dtype=np.float64)
print(b)
for d1 in b:
    np.set_printoptions(suppress=False, precision=14, floatmode='fixed')

    print('d1 float 64')
    print(np.format_float_positional(d1, precision=14, unique=False))
    print(np.format_float_scientific(d1, precision=14, unique=False))
    print()
    print(np.format_float_positional(d1, precision=14))
    print(np.format_float_scientific(d1, precision=14))
    print(np.format_float_scientific(d1, precision=14, exp_digits=4))
    print()
    print(np.format_float_positional(d1, precision=8))
    print(np.format_float_scientific(d1, precision=8))
    np.set_printoptions()
    print(np.format_float_scientific(d1, precision=8, exp_digits=4, trim='-'))
    print(np.format_float_positional(d1, precision=8, trim='-'))

# np.set_printoptions(precision=14)
print(a)


[1.40129846432482e-45 0.00000000000000e+00 1.12103877145985e-44]
zero float32
1e-45
0.00000000000000
1.e-45
1.e-0045
reset
0
zero float32
0.0
0.
0.e+00
0.e+0000
reset
0
zero float32
1.1e-44
0.00000000000000
1.1e-44
1.1e-0044
reset
0
[1.37921451557040e-311 1.37921451557040e-311 1.37921451560202e-311]
zero float64
1.3792145155704e-311
0.00000000000000
1.3792145155704e-311
1.3792145155704e-0311
reset
0
zero float64
1.3792145155704e-311
0.00000000000000
1.3792145155704e-311
1.3792145155704e-0311
reset
0
zero float64
1.379214515602e-311
0.00000000000000
1.379214515602e-311
1.379214515602e-0311
reset
0
[1.23456790519087e+17 1.23456788969634e-06]
d1 float 32
123456790519087104.00000000000000
1.23456790519087e+17

123456790000000000.
1.2345679e+17
1.2345679e+0017

123456790000000000.
1.2345679e+17
d1 float 32
0.00000123456789
1.23456788969634e-06

0.0000012345679
1.2345679e-06
1.2345679e-0006

0.00000123
1.2345679e-06
[1.23456789012346e+17 1.23456789012346e-15]
d1 float 64
123456789012345680.0

### savetxtで追記

In [6]:
import numpy

a = [[3, 4, 5], [6, 7, 8], [9, 10, 11]]
nda = numpy.array(a)

a2 = [[-3, -4, -5], [-6, -7, -8], [-9, -10, -11]]
nda2 = numpy.array(a2)

with open('output.txt', 'a') as f_handle:
    f_handle.write('test')
    numpy.savetxt(f_handle, nda)
    numpy.savetxt(f_handle, nda2)

### 1次元同士の結合で2次元配列の作成

In [53]:
import numpy as np
a1 = [1, 2, 3]
nda1 = np.array(a1)
a2 = [4, 5, 6]
nda2 = np.array(a2)

print(np.stack([nda1, nda2], axis=1))
print(np.hstack([nda1, nda2]))


[[1 4]
 [2 5]
 [3 6]]
[[1 2 3 4 5 6]]


### 1次元と2次元配列の結合

In [45]:
import numpy as np
a1 = [[3, 4, 5], [6, 7, 8], [9, 10, 11]]
nda1 = np.array(a1)
print(f'nda1:{nda1.shape} = {nda1}')


a2 = [-3, -4, -5]

nda2 = np.array(a2)
print(f'nda2:{nda2.shape} = {nda2}')

blocked_nda = np.block([[nda1], [nda2]])
print(f'{blocked_nda}:{blocked_nda.shape}')

reshaped_nd2 = nda2.reshape(len(nda2), 1)

print(np.hstack([reshaped_nd2, nda1]))

# print(np.block([nda3, nda1], 1))

nda1:(3, 3) = [[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
nda2:(3,) = [-3 -4 -5]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [-3 -4 -5]]:(4, 3)
[[-3  3  4  5]
 [-4  6  7  8]
 [-5  9 10 11]]


### numpyやfloatの数値末尾の処理
np.format_float_positional

In [ ]:
import numpy as np
step = 0.1
start = 5.0
size = 51
data = []
for i in range(size):
    data.append((step * i) + start)

u_data = []
f_data = []
t_0_data = []
t_p_data = []
t_m_data = []
print(data)

for i,value in enumerate(data):
    data[i] = np.format_float_positional(value, precision=14)
    u_data.append(np.format_float_positional(value, precision=14, unique=False))
    f_data.append(np.format_float_positional(value, precision=14, fractional=False))
    # Controls post-processing trimming of trailing digits
    t_0_data.append(np.format_float_positional(value, precision=14, trim='0'))
    t_p_data.append(np.format_float_positional(value, precision=14, trim='.'))
    t_m_data.append(np.format_float_positional(value, precision=14, trim='-'))
    
print(data)
print(u_data)
print(f_data)
print(t_0_data)
print(t_p_data)
print(t_m_data)
print(*data)



[5.0, 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6.0, 6.1, 6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7.0, 7.1, 7.2, 7.300000000000001, 7.4, 7.5, 7.6, 7.7, 7.800000000000001, 7.9, 8.0, 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9.0, 9.100000000000001, 9.2, 9.3, 9.4, 9.5, 9.600000000000001, 9.7, 9.8, 9.9, 10.0]
['5.', '5.1', '5.2', '5.3', '5.4', '5.5', '5.6', '5.7', '5.8', '5.9', '6.', '6.1', '6.2', '6.3', '6.4', '6.5', '6.6', '6.7', '6.8', '6.9', '7.', '7.1', '7.2', '7.30000000000000', '7.4', '7.5', '7.6', '7.7', '7.80000000000000', '7.9', '8.', '8.1', '8.2', '8.3', '8.4', '8.5', '8.6', '8.7', '8.8', '8.9', '9.', '9.10000000000000', '9.2', '9.3', '9.4', '9.5', '9.60000000000000', '9.7', '9.8', '9.9', '10.']
['5.00000000000000', '5.10000000000000', '5.20000000000000', '5.30000000000000', '5.40000000000000', '5.50000000000000', '5.60000000000000', '5.70000000000000', '5.80000000000000', '5.90000000000000', '6.00000000000000', '6.10000000000000', '6.20000000000000', '6.30000000000000', '

### shapeの使い方

In [47]:
import numpy as np
a1 = [[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]], [[10, 20, 30, 40], [50, 60, 70, 80], [90, 100, 110, 120]]]
nda1 = np.array(a1)
print(nda1.shape)
print(nda1.shape[1])

(2, 3, 4)
3


In [4]:
import numpy as np
def sample():
    a=[1,2,3]
    b=[[4,5],[6,7]]
    return a, b
c=[[]*i for i in range(2)]
c[0], c[1] = sample()
d=[]
f=[]

for i in range(2):
    d.extend(c[i])
    f.append(c[i])

a_copy=np.empty((3,2,3))

print(d)
print(f)
a1 = np.ones((2, 3,15), int)
print(a1)
a2 = np.full((2, 4,15), 2)
print(a2)
a0 = np.zeros((2,7,15))

print(a0)
a_b=np.empty((2,7,15))
print(f"a1[0],a2[0]=\n{a1[0]},\n{a2[0]}\n")
print(f"insert=\n{np.insert(a1[0],3,a2[0][0:4],axis=0)}\n")
print(f"a1=\n{a1}\n")
a_buf=np.vstack([a1[0],a2[0]])
print(f"vstack a1[0], a2[0]=\n{a_buf}\n")

a_b=np.vstack([a_buf,a0[0]])
print(f"a_b=\n{a_b}\n")
print(f"resize=\n{np.reshape(a_b,(2,7,15))}\n")

orig_arr=[]
ns=2
for i in range(3):
    n_arr=np.full((ns,1,15),i)
    print(f"n_arr=\n{n_arr}\n")
    for n in range(ns):
        if i == 0 == n:
            orig_arr=np.copy(n_arr[n])
            print(f"copied,n_arr{n} = \n{orig_arr},\n{n_arr[n]}\n")
        else:
            orig_arr=np.insert(orig_arr,i+(i+1)*n,n_arr[n],axis=0)
            print(f"stacked,n_arr{n} = \n{orig_arr},\n{n_arr[n]}\n")
print(f"reshape orig=\n{np.reshape(orig_arr,(ns,3,15))}")

#a_tot=np.empty((2,3))
a_tot=[]
print(f"shape={a1[0].shape}")
d1,d2,d3=a1.shape
print(f"d1,d2,d3={d1},{d2},{d3}")
print(f"dim={a1.ndim}")
print(f"size={a1.size}")
print(f"size={a1[0][:].size}")
for i,a in enumerate([a1,a2,a0]):
    if i == 0:
        a_tot=np.copy(a[0])
        print(f"atot = \n{a_tot}")
    if i > 0:
        a_tot=np.vstack([a_tot,a[0]])
        print(f"atot = \n{a_tot}")
print(f"total={a_tot}")

[1, 2, 3, [4, 5], [6, 7]]
[[1, 2, 3], [[4, 5], [6, 7]]]
[[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]]

 [[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]]]
[[[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]
  [2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]
  [2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]
  [2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]]

 [[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]
  [2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]
  [2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]
  [2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]]]
[[[0.0000000000000000 0.0000000000000000 0.0000000000000000
   0.0000000000000000 0.0000000000000000 0.0000000000000000
   0.0000000000000000 0.0000000000000000 0.0000000000000000
   0.0000000000000000 0.0000000000000000 0.0000000000000000
   0.0000000000000000 0.0000000000000000 0.0000000000000000]
  [0.0000000000000000 0.0000000000000000 0.0000000000000000
   0.0000000000000000 0.0000000000000000 0.0000000000000000
   0.0000000000000000 0.000000000000000

In [ ]:
import numpy as np
n=3
a=np.zeros((n,2,3))
print(a)
print(a[0])

def assign_func(a, i):
    a_buf=np.full((2,3),i)
    a[i]=a_buf
    del a_buf
for i in range(n):
    assign_func(a, i)
print(f"assigned a=\n{a}\n")

### スライス

In [2]:
import numpy as np
n=2
l=3
a = np.arange(n*l*3)
a = np.reshape(a, [n, l, 3])
print(f'a = {a}')
b = np.copy(a)
def assign_func(a, b, i):
    global n
    a_temp = [[[i+1 for _ in range(3)] ]for i in range(n)]
    b_temp = [[i+1 for _ in range(3)] for i in range(n)]
    print(f'a temp = {a_temp}')
    print(f'b temp = {b_temp}')
    a_buf=np.array(a_temp)
    print(f'a_buf = {a_buf}')
    print(f'a[:, i, :] = {a[:, i, :]}')
    print(f'a_buf[:, 0, :] = {a_buf[:, 0, :]}')
    a[:, i, :]=a_buf[:, 0, :]
    print(f'assigned a_buf[:, 0, :] into a[:, i, :] = {a}')
    b_buf=np.array(b_temp)
    print(f'b_buf = {b_buf}')
    print(f'b[:, i, :] = {b[:,i, :]}')
    print(f'b_buf[:, :] = {b_buf[:, :]}')
    b[:, i, :]=b_buf[:, :]
    print(f'assigned b_buf[:, :] into b[:, i, :] = {b}')

    del a_buf
    
for i in range(l):
    assign_func(a, b, i)


a = [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]
a temp = [[[1, 1, 1]], [[2, 2, 2]]]
b temp = [[1, 1, 1], [2, 2, 2]]
a_buf = [[[1 1 1]]

 [[2 2 2]]]
a[:, i, :] = [[ 0  1  2]
 [ 9 10 11]]
a_buf[:, 0, :] = [[1 1 1]
 [2 2 2]]
assigned a_buf[:, 0, :] into a[:, i, :] = [[[ 1  1  1]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 2  2  2]
  [12 13 14]
  [15 16 17]]]
b_buf = [[1 1 1]
 [2 2 2]]
b[:, i, :] = [[ 0  1  2]
 [ 9 10 11]]
b_buf[:, :] = [[1 1 1]
 [2 2 2]]
assigned b_buf[:, :] into b[:, i, :] = [[[ 1  1  1]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 2  2  2]
  [12 13 14]
  [15 16 17]]]
a temp = [[[1, 1, 1]], [[2, 2, 2]]]
b temp = [[1, 1, 1], [2, 2, 2]]
a_buf = [[[1 1 1]]

 [[2 2 2]]]
a[:, i, :] = [[ 3  4  5]
 [12 13 14]]
a_buf[:, 0, :] = [[1 1 1]
 [2 2 2]]
assigned a_buf[:, 0, :] into a[:, i, :] = [[[ 1  1  1]
  [ 1  1  1]
  [ 6  7  8]]

 [[ 2  2  2]
  [ 2  2  2]
  [15 16 17]]]
b_buf = [[1 1 1]
 [2 2 2]]
b[:, i, :] = [[ 3  4  5]
 [12 13 14]]
b_buf[:, :] = [[1 1 1]
 [2 2 2]]
a

In [ ]:
import numpy as np
n=2
l=3
a=np.zeros((n,l,3))
print(a)
print(a[0])

def assign_func(a, i):
    global n
    a_buf=np.full((n,1,3),i)
    # a[0][i]=a_buf[0]
    print(f'a_buf = {a_buf}')
    a[:,i,:]=a_buf[:,0,:]

    del a_buf
for i in range(n):
    assign_func(a, i)
print(f"assigned a=\n{a}\n")

In [ ]:
import numpy as np
arr = np.zeros([1, 3])
row = np.full((15,7), 100)
print(row)
additional = np.array([[1, 2, 3], [4, 5, 6]])
arr = np.r_[arr, additional][1:]
print(arr)


In [ ]:
a0= [1 for _ in range(2)]
print(a0)
a3=[2 for _ in range(2)]
a1 = [0 for _ in range(5)]
print(f"a1={a1}\n")
a2 = [[1,2,3],[4,5,6]]
print(f"a2=\n{a2}")
a4=['a']
a0.extend(a4)
print(f"extend={a0}\n")
a1[2]=a2

print(f"a1={a1}\n")



In [ ]:
import numpy as np
a1 = np.ones((2, 3,15), int)
print(a1)
a2 = np.full((2,4,15), 2)
print(a2)
d1=2
d2=2
row=[i+15*((d1-1)*3+(d2-1)) for i in range(15)]
print(f"row={row}")
np.put(a1,row,a2[0][0])
print(f"replaced a1=\n{a1}\n")

In [ ]:
import numpy as np
a = np.arange(50)
a = np.reshape(a,(5,10))
print(a)
b = np.arange(0, 100, 2)
b = np.reshape(b,(5,10))
print(b)
c = np.arange(50, 0,-1)
c = np.reshape(c,(5,10))
print(c)
print(f"a0=\n{a[[0]]}\n")
arr_st = np.stack([a, b, c], 1)
print(arr_st)
for aa,bb,cc in zip(a, b, c):
    arr_st = np.stack([aa, bb, cc], 1)
print(f"arr_st=\n{arr_st}\n")

In [ ]:
import numpy as np
max_number = 3
x = 2
y = 15
#test_profiler=cProfile.Profile()
#test_profiler.enable()
a_l=np.zeros((max_number,x,y))
a = np.full((3),2)
b = np.full((3),3)
variables = np.zeros((y))
a_l[0,0,0] = 1
a_l[0,0,1:4] = a
a_l[0,0,4:7] = b*2
print(a_l)

In [ ]:
import numpy as np
a = np.zeros((2,3))
print(a)
a[:,0] = 1
print(a)

print(np.sum(a[0,1:]))
print(np.sum(a[1,1:]))

In [ ]:
import numpy as np
import random

M = 2
N = 5

# サンプルデータを作る（N 次元ベクトルを M 個生成してリストに格納）
mu = [2 * np.random.rand(N, 2) - 1 for _ in range(M)]
header = [f'{i}\ncolumn1\tcolumn2' for i in range(M)]
print(header)
# N 次元ベクトルを辞書に格納する
d = {f'mu_{i}.txt': mu[i] for i in range(M)}

# 保存する
np.savez('./mu_params', **d)  # dict のアンパックが必要
#np.save('headerbin.npy', header)
np.savetxt('header.txt', header, fmt='%s')
# 読み込む
d = np.load('./mu_params.npz')  # 拡張子 .npz の指定が必要
#h = np.load('headerbin.npy')
h = np.loadtxt('header.txt', dtype='str')
# 辞書からリストを復元する
for filename,header in zip(d, h):
    np.savetxt(filename, d[filename], header=header, delimiter='\t')
#d_list = d.files  # arrayの名前リストを取得


In [ ]:
for l_n, header_l in zip(loaded_npz, header_list):
            np.savetxt(os.path.join(directory, SAVE_DIRECTORY, l_n), loaded_npz[l_n], header=header_l, delimiter='\t')

In [ ]:
import time
import numpy as np
start = time.time()
print(start)
a = ["a", "b", "c"]
np.savetxt("testsavetxt.txt",a, fmt="%s")
#for _ in range(3):
b = np.loadtxt("testsavetxt.txt", dtype="str")
print(b)
    


In [ ]:
import numpy as np
n = 5000
a = [[i for i in range(n) ] for _ in range(n)]
b = []
for x in a:
    c = []
    for y in x:
        c.append(y*2)
    b.append(c)

