# 四捨五入と有効数字

### numpy
- np.format_float_positional  
正確な四捨五入が可能だが、指数型がfloaat型に変換される
- np.around, np.round  
銀行丸め、直近の偶数に丸められる

In [ ]:
import numpy as np
np.format_float_positional(56294995342131.5, precision=3)
ls = [790.15, 799.6499999999913, 0.009999999999990905, 951, -5.502247191011237, 5.51011235955055, 0.11123595505617967, 100, 5.05699600e+02, 1.00000000e-02, 8.41726316e-01, 1.67345263e+00, 2.50517895e+00,]
for v in ls:
    print(np.format_float_positional(v, precision=10))

In [10]:
import numpy as np
np.set_printoptions(
    formatter={'float': '{:0.8e}'.format, 'int': '{:08d}'.format})


ls = [790.15, 799.6499999999913, 0.009999999999990905, 951, -5.502247191011237, 5.51011235955055, 0.11123595505617967, 100, 5.05699600e+02, 1.00000000e-02, 8.41726316e-01, 1.67345263e+00, 2.50517895e+00,]
for v in ls:
    print(np.format_float_positional(v, precision=10))

790.15
799.65
0.01
951.
-5.5022471910
5.5101123596
0.1112359551
100.
505.6996
0.01
0.841726316
1.67345263
2.50517895


In [9]:
import numpy as np

a = np.array([0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5, 9.5])
b = np.array([0.05, 0.15, 0.25, 0.35, 0.45, 0.55, 0.65, 0.75, 0.85, 0.95])

# 整数 (小数点以下0桁) に最近接丸め
print(np.around(a))
print(np.around(b, decimals=1))

print(np.round(a))
print(np.round(b, decimals=1))


[ 0.  2.  2.  4.  4.  6.  6.  8.  8. 10.]
[0.  0.2 0.2 0.4 0.4 0.6 0.6 0.8 0.8 1. ]
[ 0.  2.  2.  4.  4.  6.  6.  8.  8. 10.]
[0.  0.2 0.2 0.4 0.4 0.6 0.6 0.8 0.8 1. ]


In [ ]:
import numpy as np

a = np.array([0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5, 9.5])
b = np.array([0.05, 0.15, 0.25, 0.35, 0.45, 0.55, 0.65, 0.75, 0.85, 0.95])

# 整数 (小数点以下0桁) に最近接丸め
print(np.around(a))
print(np.around(b, decimals=1))

print(np.round(a))
print(np.round(b, decimals=1))


[ 0.  2.  2.  4.  4.  6.  6.  8.  8. 10.]
[0.  0.2 0.2 0.4 0.4 0.6 0.6 0.8 0.8 1. ]
[ 0.  2.  2.  4.  4.  6.  6.  8.  8. 10.]
[0.  0.2 0.2 0.4 0.4 0.6 0.6 0.8 0.8 1. ]
