# ソートのいろいろ

### 3次元リストでのソート

In [2]:
import numpy as np
samples = [[['dog', 2], ['cat', 1], ['ham', 4]], [['hose', 2], ['cow', 3], ['sheep', 1]]]
samples_array = np.array(samples)
# samples_array[0][][1]でソートしたsamples_array[0][]のインデックスを取得
indexs = np.argsort(samples_array[0, :, 1])
print(indexs)
# 得られたindex
print(samples_array[0][indexs])



[1 0 2]
[['cat' '1']
 ['dog' '2']
 ['ham' '4']]
[[['dog', 2], ['cat', 1], ['ham', 4]], [['hose', 2], ['cow', 3], ['sheep', 1]]]


In [6]:
import numpy as np
samples = [[['night', '2023-10-03 18:00:00'], ['noon', '2023-10-03 12:00:00'],
            ['morning', '2023-10-03 06:00:00']], [['teatime', '2023-10-03 15:00:00'], ['take_bath', '2023-10-03 21:00:00'], ['go_to_work', '2023-10-03 7:00:00']]]
samples_array = np.array(samples)
# samples_array[0][][1]でソートしたsamples_array[0][]のインデックスを取得
indexs = np.argsort(samples_array[0, :, 1])
print(indexs)
# 得られたindex
print(samples_array[0][indexs])


[2 1 0]
[['morning' '2023-10-03 06:00:00']
 ['noon' '2023-10-03 12:00:00']
 ['night' '2023-10-03 18:00:00']]


In [5]:
import numpy as np
samples = [[['night', '2023-10-03 18:00:00'], ['noon', '2023-10-03 12:00:00'],
            ['morning', '2023-10-03 06:00:00']], [['teatime', '2023-10-03 15:00:00'], ['play_game', '2023-10-04 01:00:00'], ['go_to_work', '2023-10-03 07:00:00']]]
samples_array = np.array(samples)
copied_array = np.copy(samples_array)
sorted_array = np.zeros_like(copied_array)
# samples_array[0][][1]でソートしたsamples_array[0][]のインデックスを取得
for count, sample in enumerate(samples_array):
    indexs = np.argsort(sample[:, 1])
    # 得られたindex
    print(indexs)
    print(sample[indexs])
    sorted_array[count] = sample[indexs]

print(sorted_array)



[2 1 0]
[['morning' '2023-10-03 06:00:00']
 ['noon' '2023-10-03 12:00:00']
 ['night' '2023-10-03 18:00:00']]
[2 0 1]
[['go_to_work' '2023-10-03 07:00:00']
 ['teatime' '2023-10-03 15:00:00']
 ['play_game' '2023-10-04 01:00:00']]
[[['morning' '2023-10-03 06:00:00']
  ['noon' '2023-10-03 12:00:00']
  ['night' '2023-10-03 18:00:00']]

 [['go_to_work' '2023-10-03 07:00:00']
  ['teatime' '2023-10-03 15:00:00']
  ['play_game' '2023-10-04 01:00:00']]]


- datetimeでもソートが可能

In [3]:
import numpy as np
from datetime import datetime as dt
dt_pattern = '%Y-%m-%d %H:%M:%S'
dt.strptime('2023-10-03 18:00:00', dt_pattern)
samples = [[['night', dt.strptime('2023-10-03 18:00:00', dt_pattern)], ['noon', dt.strptime('2023-10-03 12:00:00', dt_pattern)],
            ['morning', dt.strptime('2023-10-03 06:00:00', dt_pattern)]], [['teatime', dt.strptime('2023-10-03 15:00:00', dt_pattern)], 
            ['play_game', dt.strptime('2023-10-04 01:00:00', dt_pattern)], ['go_to_work', dt.strptime('2023-10-03 07:00:00', dt_pattern)]]]
samples_array = np.array(samples)
# samples_array[0][][1]でソートしたsamples_array[0][]のインデックスを取得
indexs = np.argsort(samples_array[1, :, 1])
print(f'{indexs}:{type(indexs)}')
# 得られたindexから
print(samples_array[1][indexs])



[2 0 1]:<class 'numpy.ndarray'>
[['go_to_work' datetime.datetime(2023, 10, 3, 7, 0)]
 ['teatime' datetime.datetime(2023, 10, 3, 15, 0)]
 ['play_game' datetime.datetime(2023, 10, 4, 1, 0)]]
