In [1]:
import subprocess
from subprocess import PIPE

# subprocess_cmd = ['python', 'subprocess_queue_while_test_refdocs.py', '3']
subprocess_cmd = ['python', 'subprocess_queue_while_cpubund_test_refdocs.py', '3']

proc = subprocess.run(subprocess_cmd, stdout=PIPE, stderr=PIPE)
print(proc.stdout.decode('utf-8').split('\r\n'))
print(proc.stderr.decode('utf-8').split('\n'))


In [2]:
a = 'test'
b = 'ok'
print('%s is %s' % (a, b))
print('%s is %s' % a, b)

test is ok


TypeError: not enough arguments for format string

In [18]:
import numpy as np

a = (1, [2, 3], 'test', np.array([[100, 200], [300, 400], [500, 600]]))
i, l, s, n = a
print(f'{i}, {l}, {s}, {n}')

n_b = np.array([i for i in range(18)])
n_b = n_b.reshape([3, 3, 2])
# n_b[2, :, :] = n[:, :]
print(n_b[:, 0, :])
print(n_b)

1, [2, 3], test, [[100 200]
 [300 400]
 [500 600]]
[[ 0  1]
 [ 6  7]
 [12 13]]
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]]
