In [71]:
from XAFSanalysis import XAFSanalysis_func as func

SyntaxError: invalid syntax (XAFSanalysis_func.py, line 1029)

# ipwidgetsのテスト

In [68]:
from ipywidgets import (interact, BoundedFloatText, interactive_output, HBox, VBox, Label,
                        Text, IntSlider, Layout, Checkbox, SelectMultiple, BoundedIntText,
                        Dropdown, Button, Textarea, FloatProgress, Select, IntText)
layout_objects=Layout(width='400px', height='40px')
layout_box=Layout(justify_content='flex-start')
checkbox_profiler = Checkbox(
    value=False,
    description='PROFILER: ',
    disabled=False,
    layout=layout_objects
)
checkbox_thread_fit = Checkbox(
    value=False,
    description='THREAD_FIT: ',
    disabled=False,
    layout=layout_objects
)
checkbox_optimize_fit = Checkbox(
    value=True,
    description='OPTIMIZE_FIT: ',
    disabled=False,
    layout=layout_objects
)
inttext_thread_ft = IntText(
    value=2,
    description='THREAD_FT max_workers:',
    disabled=False,
    layout=layout_objects
)
selection_data_save = Select(
    options=['TEXT','ZIP'],
    value='ZIP',
    disable=False,
    description='SAVE:',
    layout=layout_objects
)
inttext_thread_ft.style.description_width='200px'
hbox_upper = HBox([checkbox_profiler, checkbox_thread_fit, checkbox_optimize_fit])
hbox_bottoms = HBox([inttext_thread_ft, selection_data_save])
vbox_options = VBox([hbox_upper, hbox_bottoms], layout=layout_box)
display(vbox_options)

In [76]:
from ipywidgets import (interact, BoundedFloatText, interactive_output, HBox, VBox, Label,
                        Text, IntSlider, Layout, Checkbox, SelectMultiple, BoundedIntText,
                        Dropdown, Button, Textarea, FloatProgress, Select, IntText, Output)
from IPython.display import display
button = Button(description="Click Me!")
output = Output()
ch_value=True
checkbox_profiler = Checkbox(
    value=ch_value,
    description='PROFILER: ',
    disabled=False,
    layout=layout_objects
)
display(button, output,checkbox_profiler)

def on_button_clicked(b):
    with output:
        print(f"Button clicked. {checkbox_profiler.value}")

button.on_click(on_button_clicked)

Button(description='Click Me!', style=ButtonStyle())

Output()

Checkbox(value=True, description='PROFILER: ', layout=Layout(height='40px', width='400px'))

In [57]:
from collections import defaultdict
from IPython.display import HTML
import ipywidgets
from pprint import pprint
reverse_lut = defaultdict(set)
styles = set()
for export_name in dir(ipywidgets.widgets):
    export = getattr(ipywidgets.widgets, export_name)
    try:
        if issubclass(export, ipywidgets.Widget) and 'style' in export.class_trait_names():
            reverse_lut[export.style.klass.__name__].add(export.__name__)
            styles.add(export.style.klass)
    except TypeError:
        pass

html = '<ul>'
for style, widgets in reverse_lut.items():
    html = f"{html}\n<li><b>{style}:</b> {', '.join(sorted(widgets))}</li>"
html += "</ul>"
HTML(html)

In [34]:
try:
    import piplite
    await piplite.install(['ipywidgets'])
except ImportError:
    pass
import ipywidgets as widgets
a = widgets.IntSlider(description='a')
b = widgets.IntSlider(description='b')
c = widgets.IntSlider(description='c')
def f(a, b, c):
    print('{}*{}*{}={}'.format(a, b, c, a*b*c))

out = widgets.interactive_output(f, {'a': a, 'b': b, 'c': c})

widgets.HBox([widgets.VBox([a, b, c]), out])


In [ ]:
def work():
    time.sleep(0.2)
    return 1/filenumber

def run(progressbar):
    i = 0
    while True:
        print(f'task{i}_start')
        i += work()
        print(f'i={i}')
        progressbar.value = i
        progressbar.description = f'{i:.0%}'

display(label_unzip_button, unzip_progressbar)

In [ ]:
    PREFIXES = ['norm', 'chik', 'FT', 'Fit']
    savefileD = '.03/fit'
    [f'{savefileD}/{prefix}' for prefix in PREFIXES]

In [7]:
import logging
import datetime
log_date = datetime.datetime.now()
logging.basicConfig(filename = f'XAFSanalysis_func_{log_date.strftime("%Y%m%d%H%M")}.log', encoding='utf-8', level=logging.DEBUG)
logging.info(f'test\n{log_date.strftime("%Y%m%d%H%M")}')

In [3]:
a=[0]*10
print(a)
b=[i for i in range(10)]
print(b)
for i,b in enumerate(b[1:]):
    if i != 0:
        print(f'{i} is ok')
    print(f'i,b={i+1},{b}')

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
i,b=1,1
1 is ok
i,b=2,2
2 is ok
i,b=3,3
3 is ok
i,b=4,4
4 is ok
i,b=5,5
5 is ok
i,b=6,6
6 is ok
i,b=7,7
7 is ok
i,b=8,8
8 is ok
i,b=9,9


In [6]:
a = []
a.append(1)
a.append(str(a[-1])+'1')
print(a[-1])

11


In [ ]:

def a():
    global g_value
    g_value = 1
    b()
def b():
    global g_value
    g_value = 2
a()
print(g_value)

In [ ]:
a = ["a", "b", "c"]
print(a)
a = []
print(a)

In [ ]:
import os


In [ ]:
i_l = ["a", "b"]
is_l = ["a_s", "b_s"]
a_s = [1 , 2, 3]
b_s = [4 , 5, 6]
for i in zip(i_l, is_l):
    print(f'{i[0]} = {i[1]}')
    eval(f'print({i[1]})')

In [ ]:
print(f"a\\a")

In [ ]:
a=False
b=True
b = False
print(a and b is True)

print(a is b)
b=False
print(a is b)
c=True
b=c
print(a is b)
a=1
b=1
print(a is b)
a=(1,2)
b=(1,2)
print(f"is = {a is b}")
print(f"== = {a == b}")
a=[1,2]
b=[1,2]
print(f"is = {a is b}")
print(f"== = {a == b}")
b=a
print(f"is = {a is b}")


In [ ]:
a=False
b=False
c=True
print( a is True and (b or c is True))


# 関数のオーバーライド

In [ ]:
class test():
    def __init__(self,a):
        self.a = a
    def func(self):
        print(self.a)

class override(test):
    def __init__(self, a, b):
        super().__init__(a)
        self.b = b
    
    def func(self):
        super().func()
        print(self.b)

t = test('ok')
t.func()
o = override('ok','hello')
o.func()


# スレッド分割

In [1]:
import numpy as np
ini = 0
a_l = [1,2,3, 4,5]
a=np.array_split(np.array(a_l), 3)
print(a)
b = []
for aa in a:
   
    b.append(ini)
    ini+=len(aa)
print(b)

[array([1, 2]), array([3, 4]), array([5])]
[0, 2, 4]


In [2]:
import concurrent.futures
import numpy as np


test_dict={}
ini_files = [i for i in range(20, 0, -1)]
print(len(ini_files))
maxworker=7
result_array = np.empty((len(ini_files), 2, 3))
split_files = np.array_split(ini_files, maxworker)
print(f'split files = {split_files}')
ini = 0
initial_values = []
for split_file in split_files:
    initial_values.append(ini)
    ini+=len(split_file)
print(initial_values)

def threading(result_array, initial_value, files):
    print(f'ini_v, files = {initial_value}, {files}')
    for i,file in enumerate(files):
        test_arr=np.random.rand(2,3)
        test_arr[0][0]=file

        result_array[initial_value+i] = test_arr
    return initial_value

i_arr=[]

# with ThreadPoolExecutor() as executor:
with ThreadPoolExecutor(max_workers=maxworker) as executor:
    futures = {executor.submit(threading,result_array, initial_value, files):(initial_value, files) for initial_value, files in zip(initial_values, split_files)}
    for i, future in enumerate(concurrent.futures.as_completed(futures)):
    #for i,future in zip(range_i, executor.map(thread_save, range_i)):
        iterator_v, iterator_f = futures[future]
        ini_v = future.result()
        print(f"thread, inivalue, iterator value, file = {i}, {ini_v}, {iterator_v}, {iterator_f}\n")
print(result_array)

    

20
split files = [array([20, 19, 18]), array([17, 16, 15]), array([14, 13, 12]), array([11, 10,  9]), array([8, 7, 6]), array([5, 4, 3]), array([2, 1])]
[0, 3, 6, 9, 12, 15, 18]


NameError: name 'ThreadPoolExecutor' is not defined

# 関数渡し

In [ ]:
import functools
def add(a,b,c,d):
    print(f'a,b,c,d = {a},{b},{c},{d}')
def add_pertial(ta,tc):
    return functools.partial(add,a=ta, c=tc)
def test2(func,e,f):
    print(func)
    return func(b=e,d=f)

print(test2(add_pertial(1,3),2,4))

In [5]:
import functools
def add(a,b,c,d):
    print(f'a,b,c,d = {a},{b},{c},{d}')
    return [a,b,c,d]
def test2(func,e,f):
    print(func)
    return func(b=e,d=f)
basetwo = functools.partial(add,a=1, c=3)
print(test2(basetwo,2,4))



functools.partial(<function add at 0x000001F006DBE940>, a=1, c=3)
a,b,c,d = 1,2,3,4
[1, 2, 3, 4]


 - partialの中ではfor文の使用法

In [8]:
import functools
list=[5,6,7]
def add(a,b,c,d):
    print(f'a,b,c,d = {a},{b},{c},{d}')
    return [a,b,c,d]
def test2(func,e,f):
    print(func)
    for i in e:
        print(i)
        func(b=i,d=f)
#    return func(b=e,d=f)
basetwo = functools.partial(add,a=1, c=3)
print(test2(basetwo,list,4))



functools.partial(<function add at 0x000001F006C98B80>, a=1, c=3)
5
a,b,c,d = 1,5,3,4
6
a,b,c,d = 1,6,3,4
7
a,b,c,d = 1,7,3,4
None


In [ ]:
import logging
import datetime
logging.basicConfig(filename='example.log', encoding='utf-8', level=logging.DEBUG)
now=datetime.datetime.now()
logging.info(f"now={now.strftime('%H%M%S')}")

# スレッドの処理時間

In [2]:
import cProfile, pstats, io
import numpy as np
from pstats import SortKey
from concurrent.futures import ThreadPoolExecutor,ProcessPoolExecutor
import concurrent.futures
from numba import jit


max_number = 10000

test_profiler=cProfile.Profile()
test_profiler.enable()
test_dict={}
#for i in range(2500):
#    test_arr=np.random.rand(320,4)
#    test_dict[f"{i}"]=test_arr
   
    #np.save(f"testbin/testbin{i}",test_arr)
    #np.savetxt(f"testtext/testtext{i}",test_arr)
#np.savez(f"testbinall",**test_dict)
a_l=["a","b","c","d","e","f","g"]

#@jit
def thread_save(i):
    test_arr=np.random.rand(320,4)
    for j in range(320):
        for k in range(4):
            test_arr[j][k]=100
    test_arr[0][0]=i
    return i

result_array = [0 for _ in range(len(a_l))]
#print(f"result array = {result_array}\n")
i_arr=[]
range_i=range(100)
#print(range_i)
# with ThreadPoolExecutor() as executor:
with ThreadPoolExecutor() as executor:
    futures = {executor.submit(thread_save,i):i for i in range(max_number)}
    for i, future in enumerate(concurrent.futures.as_completed(futures)):
        iterator_i = futures[future]
        i_arr.append([i])
print(f"finish sequence\n")
        
test_profiler.disable()
#with open("test.prof",mode="a+") as test_profile: 

    #sortkey = SortKey.CUMULATIVE
    #ps = pstats.Stats(test_profiler, stream=test_profile).sort_stats(sortkey)
    #ps.print_stats() 
    #sortkey = SortKey.TIME  
    #ps = pstats.Stats(test_profiler, stream=test_profile).sort_stats(sortkey)
    #ps.print_callers(.5, 'init')
s = io.StringIO()    
sortkey = SortKey.CUMULATIVE
ps = pstats.Stats(test_profiler, stream=s).sort_stats(sortkey)
ps.print_stats(20) 
sortkey = SortKey.TIME  
ps = pstats.Stats(test_profiler, stream=s).sort_stats(sortkey)
ps.print_stats(20) 
ps.print_callers(.5)
print(s.getvalue())
# with np.load('filename.npz', allow_pickle=True) as loaded_records:
#    dimens = loaded_records['dimens']
#    matrices = loaded_records['matrices']


finish sequence

         563173 function calls in 5.699 seconds

   Ordered by: cumulative time
   List reduced from 114 to 20 due to restriction <20>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        9    0.000    0.000    5.698    0.633 C:\Users\admin\.conda\envs\arim-xafs\lib\site-packages\IPython\core\interactiveshell.py:3416(run_code)
        9    0.000    0.000    5.698    0.633 {built-in method builtins.exec}
        1    0.030    0.030    5.697    5.697 C:\Users\admin\AppData\Local\Temp\ipykernel_14028\3078517387.py:38(<module>)
    10001    0.039    0.000    5.274    0.001 C:\Users\admin\.conda\envs\arim-xafs\lib\concurrent\futures\_base.py:201(as_completed)
    15482    0.070    0.000    5.159    0.000 C:\Users\admin\.conda\envs\arim-xafs\lib\threading.py:280(wait)
     5608    0.049    0.000    5.150    0.001 C:\Users\admin\.conda\envs\arim-xafs\lib\threading.py:563(wait)
    61937    5.025    0.000    5.025    0.000 {method 'acquire' of '_thr

# スレッド間での変数のやり取り

In [18]:
import cProfile, pstats, io
import numpy as np
from pstats import SortKey
from concurrent.futures import ThreadPoolExecutor,ProcessPoolExecutor
import concurrent.futures
import time

start_time=time.time()
max_number = 10
x = 2
y = 15

a_l=np.zeros((max_number,x,y))
array_length = 3
variables = np.array([k for k in range(array_length)])
print(f'initial variables={variables}')

#@jit
def thread_share(i, a_l):
    global variables
    a_l[i,0,0] = i
    time.sleep(0.5)
    print(f'variables in thread{i} = {variables}')
    a_l[i,0,2:array_length+2] = variables
    variables = variables*2
    a_l[i,0,array_length+2:array_length+5] = variables
    return i

with ThreadPoolExecutor() as executor:
    futures = {executor.submit(thread_share, i, a_l):i for i in range(max_number)}
    for i, future in enumerate(concurrent.futures.as_completed(futures)):
        iterator_i = futures[future]
        a_l[iterator_i,0,1] = i
        future.result()
        print(f'i,iterator i = {i}, {iterator_i}')
np.set_printoptions(formatter={'float': '{:5.0f}'.format})      
print(f'a_l = \n{a_l}')        
print(f"finish sequence\n")

print(f'bench time = {time.time()-start_time}')
#test_profiler.disable()
#s = io.StringIO()    
#sortkey = SortKey.CUMULATIVE
#ps = pstats.Stats(test_profiler, stream=s).sort_stats(sortkey)
#ps.print_stats(20) 
#sortkey = SortKey.TIME  
#ps = pstats.Stats(test_profiler, stream=s).sort_stats(sortkey)
#ps.print_stats(20) 
#ps.print_callers(.5)
#print(s.getvalue())
#print(a_l)


       
#test_profiler.disable()
#with open("test.prof",mode="a+") as test_profile: 

    #sortkey = SortKey.CUMULATIVE
    #ps = pstats.Stats(test_profiler, stream=test_profile).sort_stats(sortkey)
    #ps.print_stats() 
    #sortkey = SortKey.TIME  
    #ps = pstats.Stats(test_profiler, stream=test_profile).sort_stats(sortkey)
    #ps.print_callers(.5, 'init')
#s = io.StringIO()    
#sortkey = SortKey.CUMULATIVE
#ps = pstats.Stats(test_profiler, stream=s).sort_stats(sortkey)
#ps.print_stats(20) 
#sortkey = SortKey.TIME  
#ps = pstats.Stats(test_profiler, stream=s).sort_stats(sortkey)
#ps.print_stats(20) 
#ps.print_callers(.5)
#print(s.getvalue())
# with np.load('filename.npz', allow_pickle=True) as loaded_records:
#    dimens = loaded_records['dimens']
#    matrices = loaded_records['matrices']


initial variables=[0 1 2]
variables in thread1 = [0 1 2]variables in thread2 = [0 1 2]
variables in thread4 = [0 2 4]

variables in thread0 = [ 0  8 16]
variables in thread3 = [ 0 16 32]
i,iterator i = 0, 4
i,iterator i = 1, 1
i,iterator i = 2, 0
i,iterator i = 3, 2
i,iterator i = 4, 3
variables in thread7 = [ 0 32 64]
variables in thread6 = [ 0 32 64]
variables in thread5 = [  0  64 128]
i,iterator i = 5, 6
i,iterator i = 6, 5
i,iterator i = 7, 7
variables in thread9 = [  0 256 512]variables in thread8 = [  0 256 512]

i,iterator i = 8, 8
i,iterator i = 9, 9
a_l = 
[[[    0     2     0     8    16     0    16    32     0     0     0
       0     0     0     0]
  [    0     0     0     0     0     0     0     0     0     0     0
       0     0     0     0]]

 [[    1     1     0     4     8     0     8    16     0     0     0
       0     0     0     0]
  [    0     0     0     0     0     0     0     0     0     0     0
       0     0     0     0]]

 [[    2     3     0     1     2   

In [12]:
import cProfile, pstats, io
import numpy as np
from pstats import SortKey
from concurrent.futures import ThreadPoolExecutor,ProcessPoolExecutor
import concurrent.futures
import time

start_time=time.time()
max_number = 10
x = 2
y = 15
#test_profiler=cProfile.Profile()
#test_profiler.enable()
a_l=np.zeros((max_number,x,y))
array_length = 3
variables = np.array([k for k in range(array_length)])
print(variables)

#@jit
def thread_share(i, a_l, variables):
    #global variables
    a_l[i,0,0] = i
    time.sleep(0.5)
    print(variables)
    a_l[i,0,2:array_length+2] = variables
    variables = variables*2
    a_l[i,0,array_length+2:array_length+5] = variables
    return i

with ThreadPoolExecutor() as executor:
    futures = {executor.submit(thread_share, i, a_l, variables):i for i in range(max_number)}
    for i, future in enumerate(concurrent.futures.as_completed(futures)):
        iterator_i = futures[future]
        a_l[iterator_i,0,1] = i
        future.result()
        print(f'i,iterator i = {i}, {iterator_i}')
        
print(f'a_l = \n{a_l}')        
print(f"finish sequence\n")

print(f'bench time = {time.time()-start_time}')



[0 1 2]
[0 1 2][0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]

[0 1 2]
[0 1 2]
i,iterator i = 0, 6
i,iterator i = 1, 2
i,iterator i = 2, 1
i,iterator i = 3, 5
i,iterator i = 4, 0
i,iterator i = 5, 4
i,iterator i = 6, 7
i,iterator i = 7, 3
[0 1 2]
i,iterator i = 8, 9
[0 1 2]
i,iterator i = 9, 8
a_l = 
[[[0. 4. 0. 1. 2. 0. 2. 4. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[1. 2. 0. 1. 2. 0. 2. 4. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[2. 1. 0. 1. 2. 0. 2. 4. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[3. 7. 0. 1. 2. 0. 2. 4. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[4. 5. 0. 1. 2. 0. 2. 4. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[5. 3. 0. 1. 2. 0. 2. 4. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[6. 0. 0. 1. 2. 0. 2. 4. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[7.

# numpyの処理時間

In [ ]:
import cProfile, pstats, io
import numpy as np
from pstats import SortKey
from concurrent.futures import ThreadPoolExecutor,ProcessPoolExecutor
import concurrent.futures
from numba import jit


max_number = 100000
x = 1
y = 15
test_profiler=cProfile.Profile()
test_profiler.enable()
test_dict={}

a_l=np.empty([max_number,x,y])


#@jit
def thread_save_sliced(i,a_l):
    n = [i*k for k in range(10)]
    for j in range(x):
             a_l[i,j,0:10] = n
    return i

def thread_save(i,a_l):
    n = [i*k for k in range(10)]
    for j in range(x):
             a_l[i][j][0] = n[0]
             a_l[i][j][1] = n[1]
             a_l[i][j][2] = n[2]
             a_l[i][j][3] = n[3]
             a_l[i][j][4] = n[4]
             a_l[i][j][5] = n[5]
             a_l[i][j][6] = n[6]
             a_l[i][j][7] = n[7]
             a_l[i][j][8] = n[8]
             a_l[i][j][9] = n[9]
    return i

result_array = [0 for _ in range(len(a_l))]
#print(f"result array = {result_array}\n")
i_arr=[]
range_i=range(100)
#print(range_i)
# with ThreadPoolExecutor() as executor:
with ThreadPoolExecutor() as executor:
    #futures = {executor.submit(thread_save,i,a_l):i for i in range(max_number)}
    futures = {executor.submit(thread_save_sliced,i,a_l):i for i in range(max_number)}
    for i, future in enumerate(concurrent.futures.as_completed(futures)):
        iterator_i = futures[future]
        i_arr.append([i])
print(f"finish sequence\n")
        
test_profiler.disable()
#with open("test.prof",mode="a+") as test_profile: 

    #sortkey = SortKey.CUMULATIVE
    #ps = pstats.Stats(test_profiler, stream=test_profile).sort_stats(sortkey)
    #ps.print_stats() 
    #sortkey = SortKey.TIME  
    #ps = pstats.Stats(test_profiler, stream=test_profile).sort_stats(sortkey)
    #ps.print_callers(.5, 'init')
s = io.StringIO()    
sortkey = SortKey.CUMULATIVE
ps = pstats.Stats(test_profiler, stream=s).sort_stats(sortkey)
ps.print_stats(20) 
sortkey = SortKey.TIME  
ps = pstats.Stats(test_profiler, stream=s).sort_stats(sortkey)
ps.print_stats(20) 
ps.print_callers(.5)
print(s.getvalue())
# with np.load('filename.npz', allow_pickle=True) as loaded_records:
#    dimens = loaded_records['dimens']
#    matrices = loaded_records['matrices']
#print(a_l)

           thread_save_sliced  max=10000 306913 function calls in 0.578 seconds
                               max=100000  2839512 function calls in 4.198 seconds
           thread_save         max=10000303222 function calls in 0.729 seconds
                               max=100000 2842142 function calls in 4.534 seconds
     

In [22]:
import cProfile, pstats, io
import numpy as np
from pstats import SortKey
from numba import jit, njit
import time
from numba.typed import List


max_number = 3
x = 1
y = 15

#test_profiler=cProfile.Profile()
#test_profiler.enable()
#a_l=np.zeros((max_number,x,y))
#print(a_l)
a_l=np.empty([max_number,x,y])
#print(a_l)
ns = [k for k in range(10)]
n = np.array(ns)
#typed_n = List()
#[typed_n.append(n) for n in ns]
start_time=time.time()
@jit 
def save_sliced(i, a_l, n):
    n = [i*k for k in range(10)]
    for j in range(x):
             a_l[i,j,0:10] = n
    return i
@jit
def save_index(i,a_l):
    #n = [i*k for k in range(10)]
    for j in range(x):
             a_l[i][j][0] = n[0]
             a_l[i][j][1] = n[1]
             a_l[i][j][2] = n[2]
             a_l[i][j][3] = n[3]
             a_l[i][j][4] = n[4]
             a_l[i][j][5] = n[5]
             a_l[i][j][6] = n[6]
             a_l[i][j][7] = n[7]
             a_l[i][j][8] = n[8]
             a_l[i][j][9] = n[9]
    return i
for i in range(max_number):
    save_sliced(i ,a_l, n)
    #save_index(i ,a_l )
print(f'bench time = {time.time()-start_time}')
#test_profiler.disable()
#s = io.StringIO()    
#sortkey = SortKey.CUMULATIVE
#ps = pstats.Stats(test_profiler, stream=s).sort_stats(sortkey)
#ps.print_stats(20) 
#sortkey = SortKey.TIME  
#ps = pstats.Stats(test_profiler, stream=s).sort_stats(sortkey)
#ps.print_stats(20) 
#ps.print_callers(.5)
#print(s.getvalue())
#print(a_l)

bench time = 0.27270960807800293


- save_sliced
    - max_number = 1000000:  1.101914405822754     
        - @jit:  3.19773530960083
        - cprofile: 3.55
        - cprofile,@jit: 2.5
- save_index  
    - max_number = 1000000:  5.5
        - @jit: 1.2
        - cprofile: 6.1
        - cprofile,@jit: 2.75
### no array
- save_index 
    - max_number = 1000000:  4.4
        - @jit: 
        - cprofile: 
        - cprofile,@jit: 

In [89]:
import cProfile, pstats, io
import numpy as np
from pstats import SortKey
from numba import jit
import time

max_number = 1000000
x = 2
y = 15
#test_profiler=cProfile.Profile()
#test_profiler.enable()
a_l=np.zeros((max_number,x,y))
#a_l=np.empty([max_number,x,y])
#print(a_l)
ns = [k for k in range(10)]
n = np.array(ns)
start_time=time.time()
#@jit
def save_sliced(i, a_l, n):
    #n = [i*k for k in range(10)]
    for j in range(x):
             a_l[i,j,0:10] = n
    return i
#@jit
def save_index(i, a_l, n):
    #n = [i*k for k in range(10)]
    for j in range(x):
             a_l[i][j][0] = n[0]
             a_l[i][j][1] = n[1]
             a_l[i][j][2] = n[2]
             a_l[i][j][3] = n[3]
             a_l[i][j][4] = n[4]
             a_l[i][j][5] = n[5]
             a_l[i][j][6] = n[6]
             a_l[i][j][7] = n[7]
             a_l[i][j][8] = n[8]
             a_l[i][j][9] = n[9]
    return i
for i in range(max_number):
    save_sliced(i ,a_l, n)
    #save_index(i, a_l, n)
print(f'bench time = {time.time()-start_time}')
#test_profiler.disable()
#s = io.StringIO()    
#sortkey = SortKey.CUMULATIVE
#ps = pstats.Stats(test_profiler, stream=s).sort_stats(sortkey)
#ps.print_stats(20) 
#sortkey = SortKey.TIME  
#ps = pstats.Stats(test_profiler, stream=s).sort_stats(sortkey)
#ps.print_stats(20) 
#ps.print_callers(.5)
#print(s.getvalue())
#print(a_l)

bench time = 1.6899394989013672


- save_index 
    - max_number = 1000000:  
        - no pass argument def save_index(i): 11.8
        - pass argument def save_index(i, a_l, n): 11.0
        - @jit: 1.0
        - cprofile: 11.3
        - cprofile,@jit: 2.3
        
- save_sliced
    - max_number = 1000000:  1.7
        - @jit:  0.9
        - cprofile: 2.0
        - cprofile,@jit: 2.1
 

- save_sliced
    - max_number = 10000:     20112 function calls in 0.039 seconds
    - max_number = 100000:    200112 function calls in 0.406 seconds
        - @jit:     369286 function calls (351399 primitive calls) in 0.554 seconds
- save_index
    - max_number = 10000:      20112 function calls in 0.075 seconds
    - max_number = 100000:    200112 function calls in 0.748 seconds
        - @jit:      771251 function calls (728326 primitive calls) in 0.858 seconds

In [ ]:
import cProfile, pstats, io
import numpy as np
from pstats import SortKey
from concurrent.futures import ThreadPoolExecutor,ProcessPoolExecutor
import concurrent.futures

test_profiler=cProfile.Profile()
test_profiler.enable()
test_dict={}
#for i in range(2500):
#    test_arr=np.random.rand(320,4)
#    test_dict[f"{i}"]=test_arr
   
    #np.save(f"testbin/testbin{i}",test_arr)
    #np.savetxt(f"testtext/testtext{i}",test_arr)
#np.savez(f"testbinall",**test_dict)
a_l=["a","b","c","d","e","f","g"]
def thread_save(i):
    test_arr=np.random.rand(320,4)
    test_arr[0][0]=i
    np.savetxt(f"testtext/testtext{i}",test_arr)
    return i
result_array = [0 for _ in range(len(a_l))]
print(f"result array = {result_array}\n")
i_arr=[]
range_i=range(100)
print(range_i)
# with ThreadPoolExecutor() as executor:
with ThreadPoolExecutor() as executor:
    #futures = {executor.submit(thread_save,i):i for i in range(100)}
    for i, future in enumerate(concurrent.futures.as_completed(futures)):
    #for i,future in zip(range_i, executor.map(thread_save, range_i)):
        iterator_i, iterator_d = futures[future]
        #iterator_i = futures[future]
        #future.result()
        #future.result()
        #print(f"iterator i, d, future={iterator_i}, {iterator_d}, {future}\n")
        # correct_number = a_l.index(as_comp)
        #print(f"thread, iterator i = {i}, {iterator_i}\n")
        #i_arr.append([i, iterator_i])
        i_arr.append([i])
        #returned_i,str=future.result()
        #print(f"results={future.result()}")
        #result_array[returned_i]=str
        #print(f"{i}-restult i, str={returned_i}, {str}\n")
#print(f"final results = \n{result_array}\n")
print(f"i_arr = {i_arr}\n")
print(f"finish sequence\n")
        
test_profiler.disable()
with open("test.prof",mode="a+") as test_profile: 
    sortkey = SortKey.CUMULATIVE
    ps = pstats.Stats(test_profiler, stream=test_profile).sort_stats(sortkey)
    ps.print_stats() 
    sortkey = SortKey.TIME  
    ps = pstats.Stats(test_profiler, stream=test_profile).sort_stats(sortkey)
    ps.print_callers(.5, 'init')

# with np.load('filename.npz', allow_pickle=True) as loaded_records:
#    dimens = loaded_records['dimens']
#    matrices = loaded_records['matrices']


In [ ]:
import cProfile, pstats, io
import numpy as np
from pstats import SortKey
from concurrent.futures import ThreadPoolExecutor,ProcessPoolExecutor
import concurrent.futures
test_profiler=cProfile.Profile()
test_profiler.enable()
test_dict={}
#for i in range(2500):
#    test_arr=np.random.rand(320,4)
#    test_dict[f"{i}"]=test_arr
   
    #np.save(f"testbin/testbin{i}",test_arr)
    #np.savetxt(f"testtext/testtext{i}",test_arr)
#np.savez(f"testbinall",**test_dict)
a_l=["a","b","c","d","e","f","g"]
def thread_save(i):
    test_arr=np.random.rand(320,4)
    test_arr[0][0]=i
    np.savetxt(f"testtext/testtext{i}",test_arr)
    return i
result_array = [0 for _ in range(len(a_l))]
print(f"result array = {result_array}\n")
i_arr=[]
#with ThreadPoolExecutor() as executor:
with ProcessPoolExecutor() as executor:
    futures = {executor.submit(thread_save,i):i for i in range(100)}
    for i, future in enumerate(concurrent.futures.as_completed(futures)):
        #iterator_i, iterator_d = futures[future]
        iterator_i = futures[future]
        future.result()
        #future.result()
        #print(f"iterator i, d, future={iterator_i}, {iterator_d}, {future}\n")
        # correct_number = a_l.index(as_comp)
        #print(f"thread, iterator i = {i}, {iterator_i}\n")
        i_arr.append([i, iterator_i])
        #returned_i,str=future.result()
        #print(f"results={future.result()}")
        #result_array[returned_i]=str
        #print(f"{i}-restult i, str={returned_i}, {str}\n")
#print(f"final results = \n{result_array}\n")
print(f"i_arr = {i_arr}\n")
print(f"finish sequence\n")
        
test_profiler.disable()
with open("test.prof",mode="a+") as test_profile: 
    sortkey = SortKey.CUMULATIVE
    ps = pstats.Stats(test_profiler, stream=test_profile).sort_stats(sortkey)
    ps.print_stats() 
    sortkey = SortKey.TIME  
    ps = pstats.Stats(test_profiler, stream=test_profile).sort_stats(sortkey)
    ps.print_callers(.5, 'init')

# with np.load('filename.npz', allow_pickle=True) as loaded_records:
#    dimens = loaded_records['dimens']
#    matrices = loaded_records['matrices']


In [ ]:
import matplotlib.pyplot as plt
import random
import os
import datetime
import psutil
import csv
import numpy as np
from concurrent.futures import ThreadPoolExecutor, ProcessPoolExecutor
import time

num_graph = 1000


range_val = 100

def loopCalc1(i):
    for j in range(range_val):
        test_arr=np.random.rand(320,4)
        test_arr[0][0]=i
        np.savetxt(f"testtext/testtext{i}",test_arr)	
        #print(f'Thread1: {i}-{j}')

if __name__ == '__main__':
    time_start = time.time()
    
    # with ProcessPoolExecutor(max_workers=4) as executor:
    with ThreadPoolExecutor(max_workers=4) as executor:
        for i in range(range_val):
            executor.submit(loopCalc1, i)
    
    time_end = time.time()
    
    print(f'{round(time_end-time_start,3)} sec')

In [ ]:
import concurrent.futures
import urllib.request

URLS = ['http://www.foxnews.com/',
        'http://www.cnn.com/',
        'http://europe.wsj.com/',
        'http://www.bbc.co.uk/',
        'http://some-made-up-domain.com/']

# Retrieve a single page and report the URL and contents
def load_url(url, timeout):
    with urllib.request.urlopen(url, timeout=timeout) as conn:
        return conn.read()

# We can use a with statement to ensure threads are cleaned up promptly
with concurrent.futures.ThreadPoolExecutor(max_workers=5) as executor:
    # Start the load operations and mark each future with its URL
    future_to_url = {executor.submit(load_url, url, 60): url for url in URLS}
    for future in concurrent.futures.as_completed(future_to_url):
        url = future_to_url[future]
        print(f"future,url,to_url={future},{url}\n{future_to_url}\n")
        try:
            data = future.result()
        except Exception as exc:
            print('%r generated an exception: %s' % (url, exc))
        else:
            print('%r page is %d bytes' % (url, len(data)))

In [ ]:
import threading
from concurrent.futures import (ThreadPoolExecutor, wait)


    
def Counter():
    lock = threading.Lock()
    count=0
    for _ in range(1_000_000):
        
        #with lock:
        count += 1
    print(count)
    return count


def main():
    counter = Counter()
    with ThreadPoolExecutor() as executor:
        features = [executor.submit(counter) for _ in range(3)]
    print(counter)

main()

In [ ]:

import time
import functools
from concurrent.futures import ProcessPoolExecutor

def call_slow_request():
    count = 0
    for i in range(10):
        time.sleep(0.1)
        count += 1
    count+=1
    for i in range(10):
        time.sleep(0.1)
        count += 1
    print(count)
    return 'ok'

def processing_time(func):
    @functools.wraps(func)
    def wrapper(*args, **keywords):
        st = time.time()  # 開始前の時間を記録
        result = func(*args, **keywords)  # 関数を実行
        print(f'time: {time.time() - st} s')  # 開始後の時間と開始前の時間の差を出力
        return result

    return wrapper

@processing_time
def run_concurrent():
    with ProcessPoolExecutor() as executor:
        features = [executor.submit(call_slow_request) for _ in range(3)]
        for feature in features:
            print(feature.result())


run_concurrent()

# line_profiler

In [ ]:
    import line_profiler
    import numpy as np
    profile = line_profiler.LineProfiler()
    profile.enable_by_count()
    a=np.empty([2,3])
    profile.disable_by_count()
    profile.print_stats()

In [ ]:
    import line_profiler
    import numpy as np
    profile = line_profiler.LineProfiler()
    profile.create_stats()
    stats = DjangoDebugToolbarStats(profile)
        if DJ_PROFILE_USE_LINE_PROFILER:
            stats.line_stats = self.line_profiler.get_stats()
        self.stats.calc_callees()
    profile.enable_by_count()
    a=np.empty([2,3])
    profile.disable_by_count()
    profile.print_stats()

In [ ]:
import random
import threading
import time

from line_profiler import LineProfiler


def do_other_stuff(numbers):
    time.sleep(1)
    s = sum(numbers)


def do_stuff(numbers):
    my_thread = threading.Thread(target=do_other_stuff, args=[numbers])
    my_thread.start()
    my_thread.join()


thread_to_lp = {}


def wrapper_in_thread(func):
    def inner(*args, **kwargs):
        lp = thread_to_lp.setdefault(threading.current_thread(), LineProfiler())
        lp.add_function(func)
        lp.enable_by_count()
        try:
            return func(*args, **kwargs)
        finally:
            lp.disable_by_count()

    return inner


do_other_stuff = wrapper_in_thread(do_other_stuff)
do_stuff = wrapper_in_thread(do_stuff)

numbers = [random.randint(1, 100) for i in range(1000)]
do_stuff(numbers)

for lp in thread_to_lp.values():
    lp.print_stats()

In [ ]:
import line_profiler 

# 変数スコープ

In [3]:

def funca():
    a = 3
    print(a)

def funcb():
    global a
    b = 5
    b = a
    print(b)

funcb()


3


# bearar認証

eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6Ii1VRWFUdFBrRE9aRkZwMkh0WURyeVZTODQxZDhlQmlPZXhreEpWZ2N6TFEifQ.eyJpc3MiOiJodHRwczovL2RpY2Vsb2dpbi5iMmNsb2dpbi5jb20vMGU5ZDUxZDEtYjg1MS00ZWE1LWI0YzktZmFkY2UyYzhjOGIwL3YyLjAvIiwiZXhwIjoxNjc5MDI5NzY5LCJuYmYiOjE2NzkwMjYxNjksImF1ZCI6ImRhMmJiMTgxLTNkZTItNDQ2ZS05ZTI3LWMyYTIzMDY5ZWU2OSIsImlkcCI6Imh0dHBzOi8vZGljZWlkbS5uaW1zLmdvLmpwIiwic3ViIjoiYTE3NTk2ODZmYmRmZmQ1ZDY0MTgxY2ZlNTE1NmYyYzJlYjA3ZTEwNzY0M2VlNTIyYzgyNDUyYTYiLCJuYW1lIjoi6Jek5bed6Kqg5Y-4IiwiZmFtaWx5X25hbWUiOiJmdWppa2F3YSIsImdpdmVuX25hbWUiOiJzZWlqaSIsIm1pZGRsZV9uYW1lIjoiIiwibm9uY2UiOiJhZjdmYmM3Yi03NTdiLTQ1OTUtYWU4OC0wNjFhNGEwOGI0ZWEiLCJzY3AiOiJ1c2Vycy5yZWFkIG1hdGVyaWFscy53cml0ZSBtYXRlcmlhbHMucmVhZCBpbnN0cnVtZW50cy5yZWFkIGRhdGFzZXRzLnJlYWQgZW50cmllcy53cml0ZSBlbnRyaWVzLnJlYWQiLCJhenAiOiI1Njg3ZWQ4Yy1mOTAxLTQ4NmItODkwNS01YWZjOTNlNDM0NDUiLCJ2ZXIiOiIxLjAiLCJpYXQiOjE2NzkwMjYxNjl9.hTDffHR8DPNlyBhN723zvOvOFCM6THPNhcHC1mS0ww8ckThdgd3ZGU41lDFOcbSzcdAroVzlYCUnUX2Swn9krwQeoZOFrdrYApeZtsXbP0fHoJWCq5KWW8jmoWfVdAYuGqbd-lRq9QBFzijMCGNP0IW86-sY68Z1caXktQ00Ul7giVmb3FsdXNCKv7M_1rhYivIT2To3Gep52CbSBE3EPWQvmhCdkMK1c0KoYgRz5axZ28bSSQsy6B0GimZqhhceqAkhMMOiU3zacQNgszgXQ6yKnrKdjfiE6Mz9EIhiFhIH6UIJvDfk2UUEjyoswRkm0BE9lJSlLBnAhR5E8lIksA

# logging　低度

In [1]:
import logging
logging.basicConfig(filename = f'test.log', encoding='utf-8', level=logging.DEBUG)
print('logging start')
logging.info('info')
logging.debug('debug')

logging start


# Outlook予定を挿入